/** Do'kon mock ma'lumotlari — MongoDB ga seed */
export const categories = [
  { externalId: "1", name: "Oshxona", slug: "oshxona", image: "/images/categories/oshxona.jpg", count: 24 },
  { externalId: "2", name: "Yotoqxona", slug: "yotoqxona", image: "/images/categories/yotoqxona.jpg", count: 18 },
  { externalId: "3", name: "Ofis", slug: "ofis", image: "/images/categories/ofis.jpg", count: 12 },
  { externalId: "4", name: "Mehmonxona", slug: "mehmonxona", image: "/images/categories/mehmonxona.jpg", count: 15 },
  { externalId: "5", name: "Bolalar", slug: "bolalar", image: "/images/categories/bolalar.jpg", count: 8 },
];

export const products = [
  {
    externalId: "1",
    name: "Oshxona mebellari to'plami Premium",
    category: "Oshxona",
    price: 12500000,
    material: "MDF 18mm, Laminat",
    width: 320,
    depth: 60,
    height: 220,
    description:
      "Zamonaviy dizayndagi to'liq oshxona mebellari to'plami. Yuqori sifatli MDF va laminat qoplamasi. 5 yillik kafolat.",
    image: "/images/products/1.jpg",
    images: ["/images/products/1.jpg", "/images/products/7.jpg"],
    rating: 4.8,
    reviews: 124,
    isPopular: true,
    isRecommended: true,
  },
  {
    externalId: "2",
    name: "Yotoqxona shkafi 3 eshikli",
    category: "Yotoqxona",
    price: 4800000,
    material: "MDF 18mm",
    width: 180,
    depth: 60,
    height: 220,
    description: "Keng hajmli 3 eshikli shkaf. Ichki bo'limlar va tortma tizimi.",
    image: "/images/products/2.jpg",
    images: ["/images/products/2.jpg"],
    rating: 4.6,
    reviews: 89,
    isNew: true,
    isRecommended: true,
  },
  {
    externalId: "3",
    name: "Ofis stoli ergonomik",
    category: "Ofis",
    price: 2100000,
    material: "Yog'och, metall",
    width: 140,
    depth: 70,
    height: 75,
    description: "Zamonaviy ofis stoli. Kabel boshqaruv tizimi bilan.",
    image: "/images/products/3.jpg",
    images: ["/images/products/3.jpg"],
    rating: 4.5,
    reviews: 56,
    isPopular: true,
  },
  {
    externalId: "4",
    name: "Divan to'plami L-shakl",
    category: "Mehmonxona",
    price: 8900000,
    material: "Mato, Yog'och",
    width: 280,
    depth: 180,
    height: 85,
    description: "Qulay L-shakl divan. Yumshoq mato qoplamasi.",
    image: "/images/products/4.jpg",
    images: ["/images/products/4.jpg"],
    rating: 4.9,
    reviews: 203,
    isPopular: true,
    isRecommended: true,
  },
  {
    externalId: "5",
    name: "Bolalar shkafi rangli",
    category: "Bolalar",
    price: 3500000,
    material: "MDF, emal",
    width: 120,
    depth: 50,
    height: 180,
    description: "Bolalar xonasi uchun xavfsiz va rang-barang shkaf.",
    image: "/images/products/5.jpg",
    images: ["/images/products/5.jpg"],
    rating: 4.7,
    reviews: 42,
    isNew: true,
  },
  {
    externalId: "6",
    name: "TV stendi minimal",
    category: "Mehmonxona",
    price: 1800000,
    material: "Laminat",
    width: 180,
    depth: 40,
    height: 50,
    description: "Minimal dizayndagi TV stendi. Kabel yashirish joyi.",
    image: "/images/products/6.jpg",
    images: ["/images/products/6.jpg"],
    rating: 4.4,
    reviews: 31,
    isNew: true,
  },
  {
    externalId: "7",
    name: "Oshxona oroli markaziy",
    category: "Oshxona",
    price: 6200000,
    material: "Granit, MDF",
    width: 240,
    depth: 90,
    height: 90,
    description: "Granit ustunli markaziy oshxona oroli.",
    image: "/images/products/7.jpg",
    images: ["/images/products/7.jpg"],
    rating: 4.8,
    reviews: 67,
    isRecommended: true,
  },
  {
    externalId: "8",
    name: "Yotoq komplekti",
    category: "Yotoqxona",
    price: 5400000,
    material: "Yog'och, mato",
    width: 160,
    depth: 200,
    height: 100,
    description: "Yotoq, 2 ta tungi stol va bosh stol to'plami.",
    image: "/images/products/8.jpg",
    images: ["/images/products/8.jpg"],
    rating: 4.6,
    reviews: 78,
    isPopular: true,
  },
];

export const userOrders = [
  {
    orderNumber: "12578",
    date: "2026-05-18",
    total: 12500000,
    status: "jarayonda",
    customerName: "Demo mijoz",
    items: [{ name: "Oshxona mebellari to'plami Premium", quantity: 1 }],
  },
  {
    orderNumber: "12560",
    date: "2026-04-02",
    total: 4800000,
    status: "tugallangan",
    customerName: "Demo mijoz",
    items: [{ name: "Yotoqxona shkafi 3 eshikli", quantity: 1 }],
  },
];

export const defaultChat = {
  threadId: "main",
  customerName: "Mijoz",
  status: "kelishuv",
  customerAgreed: false,
  adminAgreed: false,
  messages: [
    {
      id: "msg-1",
      sender: "admin",
      text: "Assalomu alaykum! Mebellarga xush kelibsiz. Qanday yordam bera olaman?",
      createdAt: new Date().toISOString(),
    },
  ],
  activeSketch: null,
  adminLastSeenAt: null,
  orderRound: 1,
};
